### ISSUE TITLE
Cannot be used on headless Linux

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/emacs-feedstock#11]
If you try to use emacs in a headless Linux, even with `-nw`, you get `emacs: error while loading shared libraries: libXpm.so.4: cannot open shared object file: No such file or directory`, because it links against X. I don't know if there is some way to make it just work in this situation. If not, we could perhaps build a package with a special `nox` feature that is compiled with `--without-x`.

**Comment by ocefpaf** [comment]
We have x11 packages on conda-forge now. Maybe we should remove the yum
requirements and use those instead.

**Comment by asmeurer** [comment]
Really? That's impressive it it works.

**Comment by asmeurer** [comment]
What are the packages called? `conda install x11` didn't work.

**Comment by ocefpaf** [comment]
I  believe you only need
https://github.com/conda-forge/xorg-libxaw-feedstock for this feedstock.

(search for xorg in the conda-forge org to see all.)

On Mar 7, 2017 6:22 PM, "Aaron Meurer" <notifications@github.com> wrote:

What are the packages called? conda install x11 didn't work.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/emacs-feedstock/issues/11#issuecomment-284863321>,
or mute the thread

**Comment by asmeurer** [comment]
Well how about that. I installed xorg-libxpm and xorg-libxaw and `emacs -nw` works now. And it even opens a graphical emacs when I ssh with `-X`.

**Comment by asmeurer** [comment]
Here's `conda inspect linkages emacs` output with those packages installed:

```
emacs
-----

conda-forge::giflib-5.1.4-0:
    libgif.so.7 (lib/libgif.so.7)

conda-forge::icu-58.1-1:
    libicudata.so.58 (lib/libicudata.so.58)
    libicui18n.so.58 (lib/libicui18n.so.58)
    libicuuc.so.58 (lib/libicuuc.so.58)

conda-forge::jpeg-9b-0:
    libjpeg.so.9 (lib/libjpeg.so.9)

conda-forge::libiconv-1.14-4:
    libiconv.so.2 (lib/libiconv.so.2)

conda-forge::libpng-1.6.28-0:
    libpng16.so.16 (lib/libpng16.so.16)

conda-forge::libtiff-4.0.6-7:
    libtiff.so.5 (lib/libtiff.so.5)

conda-forge::libuuid-1.0.3-1:
    libuuid.so.1 (lib/libuuid.so.1)

conda-forge::libxcb-1.12-1:
    libxcb.so.1 (lib/libxcb.so.1)

conda-forge::libxml2-2.9.4-4:
    libxml2.so.2 (lib/libxml2.so.2)

conda-forge::ncurses-5.9-10:
    libtinfo.so.5 (lib/libtinfo.so.5)

conda-forge::xorg-libice-1.0.9-2:
    libICE.so.6 (lib/libICE.so.6)

conda-forge::xorg-libsm-1.2.2-2:
    libSM.so.6 (lib/libSM.so.6)

conda-forge::xorg-libx11-1.6.4-6:
    libX11-xcb.so.1 (lib/libX11-xcb.so.1)
    libX11.so.6 (lib/libX11.so.6)

conda-forge::xorg-libxau-1.0.8-3:
    libXau.so.6 (lib/libXau.so.6)

conda-forge::xorg-libxaw-1.0.13-0:
    libXaw.so.7 (lib/libXaw.so.7)

conda-forge::xorg-libxdmcp-1.1.2-3:
    libXdmcp.so.6 (lib/libXdmcp.so.6)

conda-forge::xorg-libxext-1.3.3-2:
    libXext.so.6 (lib/libXext.so.6)

conda-forge::xorg-libxmu-1.1.2-0:
    libXmu.so.6 (lib/libXmu.so.6)

conda-forge::xorg-libxpm-3.5.12-0:
    libXpm.so.4 (lib/libXpm.so.4)

conda-forge::xorg-libxt-1.1.5-0:
    libXt.so.6 (lib/libXt.so.6)

xz-5.2.2-1:
    liblzma.so.5 (lib/liblzma.so.5)

zlib-1.2.8-3:
    libz.so.1 (lib/libz.so.1)

system:
    libXfixes.so.3 (/usr/lib/x86_64-linux-gnu/libXfixes.so.3)
    libc.so.6 (/lib/x86_64-linux-gnu/libc.so.6)
    libdl.so.2 (/lib/x86_64-linux-gnu/libdl.so.2)
    libgcc_s.so.1 (/lib/x86_64-linux-gnu/libgcc_s.so.1)
    libm.so.6 (/lib/x86_64-linux-gnu/libm.so.6)
    libpthread.so.0 (/lib/x86_64-linux-gnu/libpthread.so.0)
    librt.so.1 (/lib/x86_64-linux-gnu/librt.so.1)
    libstdc++.so.6 (/usr/lib/x86_64-linux-gnu/libstdc++.so.6)
    linux-vdso.so.1 ()

not found:
```

So those are the ones we should depend on. No idea if we need to pin versions on any of them. We also should include `xorg-libxfixes` and `libgcc` as well, apparently.

**Comment by bjodah** [comment]
I just ran into this. Installing `emacs` from conda-forge gave me the following error upon launching "emacs":
```
emacs: error while loading shared libraries: libXpm.so.4: cannot open shared object file: No such file or directory
```
Running `$ conda install xorg-libxpm xorg-libxaw` changes the error to be:
```
emacs: error while loading shared libraries: libXfixes.so.3: cannot open shared object file: No such file or directory
```

what about adding a `emacs-nox` package (analogous to what debian does)?

EDIT: also installing `xorg-libxfixes` fixes it for me.

**Comment by asmeurer** [comment]
We need to add dependencies to the proper conda-forge X packages, and use conda inspect (or the newest conda build) to verify we didn't miss any. I'll probably get to it eventually, but feel free to do a PR if you want (I don't use Linux, so it's not as high priority for me as the OS X fixes).

**Comment by asmeurer** [comment]
@bjodah (or someone else), can you run

```
conda create -n test xorg-libxpm xorg-libxaw xorg-libxfixes emacs
conda inspect linkages -n test emacs
```

and paste the output here (ideally after https://github.com/conda-forge/emacs-feedstock/pull/10 is merged and built, but even on the current build it should be fine).

**Comment by bjodah** [comment]
Here's the output:
https://gist.github.com/bjodah/a0a7bf852ed4a5743d9127ea506e2698

not sure what I'm looking for...

**Comment by asmeurer** [comment]
No idea what the warnings are all about. We care about the stuff at the bottom. That tells us that those three packages are enough, because there are no linked libraries that aren't installed ("not found") and no other system linked libraries from X.

**Comment by asmeurer** [comment]
PR at https://github.com/conda-forge/emacs-feedstock/pull/18
