### ISSUE TITLE
Better work directory path replacement for OS X build

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/emacs-feedstock#20]
Right now, we have some custom stuff in the build to do a binary replacement of the work directory on OS X (see #10). This includes some [custom stuff](https://github.com/conda-forge/emacs-feedstock/blob/bda318f7ee6910d1b3cc92d235f3535d6a0a4867/.travis.yml#L54-L75) in the .travis.yml. 

Unfortunately, this means that it will have to be manually kept intact each time a rerender is done. I think it is possible to extract the CONDA_BLD_PATH environment variable to some conda-forge YAML file, but I couldn't find any documentation about it. We should also be able to remove the `--no-build-id` flag and use the default build ID, since the number is based on a timestamp and should stay a constant length (see https://github.com/conda-forge/emacs-feedstock/pull/10#discussion_r178183558).  Basically, we have to make the work directory exactly 255 characters so that we can replace it with the placehold_placehold_... prefix, so that conda does the binary prefix replacement on it. 

Alternatively, if is possible to build the GUI emacs on OS X so that it doesn't hard-code the work directory in the first place, that would be even better.

**Comment by djsutherland** [comment]
> Alternatively, if is possible to build the GUI emacs on OS X so that it doesn't hard-code the work directory in the first place, that would be even better.

That would be much better IMO. It seems like a bug in Emacs; does it mean e.g. that if you're installing manually, you can never delete the directory you compiled it in?

But, yeah, given that this bad behavior exists, of course it'd be better to be more stable across re-renders. Not sure about that.

**Comment by asmeurer** [comment]
I guess it's not needed any more for 26.1. Closing.
