### ISSUE TITLE
26.1rc1?

### ISSUE THREAD

**Issue by jamescasbon** [conda-forge/emacs-feedstock#21]
Are you interested in a build for 26 branch from git?  This is working, but a couple of tests aren't working so I commented make check.  No idea what is failing as there are 1000s of lines of warnings and its not obvious where the fail is.

```
diff --git a/recipe/build.sh b/recipe/build.sh
index c177078..99c977b 100644
--- a/recipe/build.sh
+++ b/recipe/build.sh
@@ -8,10 +8,11 @@ else
     OPTS="--x-includes=$PREFIX/include --x-libraries=$PREFIX/lib"
 fi
 
+./autogen.sh
 bash configure  --prefix=$PREFIX $OPTS
 
 make
-make check
+# make check
 make install
 
 if [ "$(uname)" == "Darwin" ]; then
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index 343802e..a9707c2 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -2,16 +2,15 @@
 # X, it is built with --without-x (terminal emacs only). Feel free to lift
 # either of these restrictions if you are able to get it to build.
 
-{% set version = "25.3" %}
+{% set version = "26.1" %}
 
 package:
   name: emacs
   version: {{ version }}
 
 source:
-  fn: emacs-{{ version }}.tar.xz
-  url: http://ftp.gnu.org/gnu/emacs/emacs-{{ version }}.tar.xz
-  sha1: 1cb4f39e9c0a3305fd62f936c7c95ff8e2924323
+  git_rev: emacs-26.1-rc1
+  git_url: https://github.com/emacs-mirror/emacs.git

 build:
   number: 2
@@ -20,6 +19,7 @@ build:
 
 requirements:
   build:
+    - autoconf
     - toolchain
     - libxml2 2.9.*
     - ncurses 5.9*

```

**Comment by asmeurer** [comment]
What is the conda-forge policy on pre-releases? @conda-forge/core 

I think a PR would be worth it, at least to see if it works, and what those make check errors are.

**Comment by ocefpaf** [comment]
We recommend to put them into a `dev` label so users can have a choice to install them or not. See the rasterio-feedstock or the gmt-feedstock for some examples on how to do this.

**Comment by asmeurer** [comment]
Also if possible it should [avoid using git](https://conda-forge.org/docs/meta.html#build-from-tarballs-not-repos).

**Comment by CJ-Wright** [comment]
We could have the recipe point at the github mirror for upsteam.

**Comment by jamescasbon** [comment]
OK, Ill address those points and submit a PR

**Comment by asmeurer** [comment]
We now have 26.1 final. If you want to build future rc releases I'm open to it, as long we follow the conda-forge policies for pre-releases.
