### ISSUE TITLE
can we update it to 29.1

### ISSUE THREAD

**Issue by beyondpie** [conda-forge/emacs-feedstock#76]
### Comment:

Hi there,

Emacs now has upgrade to 29.1, so could we also upgrade the source of conda-forge?

Thanks!
Songpeng

**Comment by asmeurer** [comment]
Yes, but some work needs to be done to make it work. See #75. I can't speak for the other maintainers here, but I likely won't have time myself to do this any time soon. If you want to give it a try feel free to make a PR.

**Comment by beyondpie** [comment]
Thanks! I totally understand! I may give it a try later in the next month if time allows.

**Comment by asmeurer** [comment]
This is done
